



<div class="row" style="margin-left: 5px">

    <h2>
        Paczka o nazwie :<b> <i><?= $this->escapeHtml($fileName) ?></i></b> został załadowana do bazy danych.
    </h2>

    <a href="<?= $this->url('files'); ?>" class="button button1" style="float: left; text-decoration: none"><b>Powrót</b></a>

</div>




<style>
table, th, td {
border: 2px solid grey;
}
</style>

<?php
if(!empty($blad))
echo "<br>" . $blad;
?>
















