<?php
$this->headTitle('Resetowanie hasła');

$form->get('email')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Email '
    ]);

$form->get('submit')->setAttributes([
    'class'=>'btn btn-large btn-primary'
    ]);

$form->prepare();
?>

<div class="row">
    <div class="col-md-offset-4 col-md-4">
        <?= $this->form()->openTag($form); ?>

        <h2>Resetowanie hasła</h2>

        <p>Podaj adres email:</p>

        <?= $this->formElement($form->get('email')); ?>
        <?= $this->formElementErrors($form->get('email')); ?>                              

        <?= $this->formElement($form->get('captcha')); ?>
        <p class="hint">Przepisz.</p>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->formElement($form->get('csrf')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>
