<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Projekt Zespołowy')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
        
        <style>
        #kontener{padding:0;}
        #menu{padding:0;}
        #tres{padding:0;}
        #nawigacja{padding:0;}
        #menu a {
            background-color: #eee;
            color: black;
            display: block;
            padding: 12px;
            text-decoration: none;
        }

        #menu a:hover {
            background-color: #ccc;
        }

        #menu a.active {
            background-color: #4CAF50;
            color: white;
        }
        
        
        
        </style>    
    </head>
    
    <body>
        
            <nav id="nawigacja" class="navbar navbar-inverse navbar-fixed-top" role="navigation" style="border-right: 5px solid green; border-top: 5px solid green; border-bottom: 5px solid green; border-left: 5px solid green;">
                <div class="container">
                        <ul class="nav navbar-nav" style="float:right;">
                            <li><a href="<?= $this->url('home') ?>" ><span class="glyphicon glyphicon-user" ></span>Zaloguj</a></li>
                        </ul>
                </div>
            </nav>

            
            
            <div id="menu" class="col-md-2" style="border-right: 5px solid red; border-top: 5px solid red; border-bottom: 5px solid red; border-left: 5px solid red; ">
                    <a href="<?= $this->url('home') ?>" class="active">Menu</a>
                    <a href="<?= $this->url('home') ?>">Home</a>
                    <a href="<?= $this->url('search') ?>">Przegladaj</a>
                    <a href="<?= $this->url('import') ?>">Importuj</a>
                    <a href="<?= $this->url('user') ?>">Zarzadzaj kontem</a>          
            </div>


            <div id="tresc" class="col-md-10" style="border-left: 5px solid blue; border-top: 5px solid blue; border-bottom: 5px solid blue; border-right: 5px solid blue;">
                <?= $this->content ?>
                <hr>
                <footer>
                    <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
                </footer>
            </div>
            
        
        <?= $this->inlineScript() ?>
    </body>
</html>
