<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Projekt Zespołowy')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
        
 
    </head>
    
    <body>
            <nav class="navbar navbar-inverse navbar-fixed-top" style="border-right: 5px solid green; border-top: 5px solid green; border-bottom: 5px solid green; border-left: 5px solid green; ">
                <div class="container-fluid">
                    
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                      </button>
                    </div>

                   <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                          <li>
                            <a><?php echo $this->mainMenu()->render();?><span class="caret"></span></a>               
                          </li>
                        </ul>
                  </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->
            </nav>
        

            <!-- Menu items-->
            <div id="menu" class=" col-md-2 " style="border-right: 5px solid red; border-top: 5px solid red; border-bottom: 5px solid red; border-left: 5px solid red; ">
                    <a href="<?= $this->url('home') ?>" class="active">Menu</a>
                    <a href="<?= $this->url('home') ?>">Informacje</a>
                    <a href="<?= $this->url('search') ?>">Przegladaj</a>
                    <a href="<?= $this->url('import') ?>">Importuj</a>
                    <a href="<?= $this->url('users') ?>">Użytkownicy</a>         
            </div>

            <!-- Content page-->
            <div id="tresc" class="col-md-10" style="border-left: 5px solid blue; border-top: 5px solid blue; border-bottom: 5px solid blue; border-right: 5px solid blue;">
                <?= $this->content ?>
                <hr>
                <footer>
                    <p>&copy;     <?= date('Y') ?> by Grupa pierwsza :-) </p>
                </footer>
            </div>
            
        
        
        
        <?= $this->inlineScript() ?>    
    </body>
</html>
